persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# 允许匿名访问（方便初期调试）
allow_anonymous true

# 监听 1883 端口 (用于手机/车侧发送数据)
listener 1883
protocol mqtt

# 监听 9001 端口 (用于网页端 WebSocket 连接)
listener 9001
protocol websockets
